name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test parser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@eeb902ac2f1be576edc296309872cf476a209b7f # v2

      - name: Install dependencies
        run: npm install

      - name: Run parser tests
        run: npm run test

  test-rust:
    name: Test Rust bindings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0

      - name: Run cargo test
        run: cargo test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@eeb902ac2f1be576edc296309872cf476a209b7f # v2

      - name: Install dependencies
        run: npm install

      - name: Check for parser generation issues
        run: |
          npm run generate
          git diff --exit-code
